In [1]:
import numpy as np

In [2]:
l=[1,2,3,5]
n1=np.array(l)

In [3]:
print("Information about the array:")
print("The array is:",n1)
print("Type of array shown is :",type(n1))
print("Data type of arrray is :",n1.dtype)
print("Shape of array given is :",n1.shape)

Information about the array:
The array is: [1 2 3 5]
Type of array shown is : <class 'numpy.ndarray'>
Data type of arrray is : int32
Shape of array given is : (4,)


In [4]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [5]:
n = np.arange(0, 30, 2) # create an array of numbers between [0,30) with an interval of 2
print(n)
print(n.ndim) #Print the dimention of the array

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
1


In [6]:
o = np.linspace(0, 10, 9) # create an array of 9 elements between [0,10]. Decide the interval according to n
print(o)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [7]:
q = np.ones((3,2))  #Create a 2D array of size (rows,columns) having all 1s
print(q)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#To have int 1s
p = np.ones((3,2), int)
print(p)

[[1 1]
 [1 1]
 [1 1]]


In [9]:
np.eye((4),dtype=int) # Identity Matrix of size (x) and datatype -> int... Float by default

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [10]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)
print(np.diag(X)) # Diagonal element array array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [11]:
np.full((2,3), 10) #Fills the whole array of size (row,column) with value mentioned (here 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [12]:
#np.random.random((row,column)) returns random floats in the interval [0.0, 1.0)
#The output points are in Uniform distribution
t1=np.random.random((2,3))
print(t1)

[[0.77009619 0.48143306 0.36425687]
 [0.00334994 0.91494012 0.85903795]]


In [13]:
np.diag((10,99,44)) #Creating a matrix with diagonal elements as mentioned and rest 0

array([[10,  0,  0],
       [ 0, 99,  0],
       [ 0,  0, 44]])

In [14]:
np.diag((10,99,44)).flatten()

array([10,  0,  0,  0, 99,  0,  0,  0, 44])

In [17]:
n = np.arange(0,30,2)
print(n)
print(n.shape)
n.reshape(3,5)
print("Print n after reshaping : ",n)
print("NO CHANGES! It creates a copy and the array remains unchanged")
l= n.reshape(3,5)
print("After storing it separately :",l,sep="\n")

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
(15,)
Print n after reshaping :  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
NO CHANGES! It creates a copy and the array remains unchanged
After storing it separately :
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [18]:
o = np.linspace(0,10,9)
print(o)
l = o.resize(3,3) # Inplace as it will return None
print(l)
print(o)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
None
[[ 0.    1.25  2.5 ]
 [ 3.75  5.    6.25]
 [ 7.5   8.75 10.  ]]


In [19]:
np.stack([[1,2], [99,100], [-45, -47]], axis=0)

array([[  1,   2],
       [ 99, 100],
       [-45, -47]])

In [20]:
np.stack([[1,2], [99,100], [-45, -47]], axis=1)

array([[  1,  99, -45],
       [  2, 100, -47]])

In [22]:
np.vstack([[1,2], [99,100], [-45, -47]])

array([[  1,   2],
       [ 99, 100],
       [-45, -47]])

In [23]:
np.hstack([[1,2], [99,100], [-45, -47]])

array([  1,   2,  99, 100, -45, -47])

In [25]:
arr1=np.array([[1,2],[11,12]])
arr2=np.array([[3,4],[31,41]])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[ 1  2  3  4]
 [11 12 31 41]]
[[ 1  2]
 [11 12]
 [ 3  4]
 [31 41]]


In [26]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
print(n1,n2,sep="\n")

[1 2 3]
[4 5 6]


In [28]:
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1**n2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [29]:
print("Array*number")
print(n1*3)
print("List*number")
print([1,2,3]*3)

Array*number
[3 6 9]
List*number
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [31]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [33]:
print("n1:",n1)
print("n2:",n2)
print("Dot product : ")
print(n1.dot(n2))
print(n2.dot(n1))

n1: [1 2 3]
n2: [4 5 6]
Dot product : 
32
32


In [38]:
l = [[1,2,3],[2,2,3],[9,0,8]]
q = np.array(l)
print(q)

[[1 2 3]
 [2 2 3]
 [9 0 8]]


In [39]:
print(q.argmax(axis=0))

[2 0 2]


In [40]:
print(q.argmax(axis=1))

[2 2 0]


In [43]:
q.dtype

dtype('int32')

In [44]:
q=q.astype('f')
print(q.dtype)

float32


In [45]:
a = np.array([-4,-3,-1,5,19])

In [46]:
print(a)
print("Max:", a.max())
print("Min:", a.min())
print("Mean:", a.mean())
print("Std:", a.std())
print("Index of Max Value:", a.argmax())
print("Max Value", a[a.argmax()])
print("Index of Min Value:", a.argmin())

[-4 -3 -1  5 19]
Max: 19
Min: -4
Mean: 3.2
Std: 8.49470423263812
Index of Max Value: 4
Max Value 19
Index of Min Value: 0


In [47]:
b = np.array([[1,99,20,31],[-1,-24,37,-13],[-7,11,49,4]])

In [48]:
print(b, end='\n\n')

print("Max:", b.max())
print("Min:", b.min())
print("Mean:", b.mean())
print("Std:", b.std())
print("Index of Max Value:", b.argmax()) # Returns position of the flattened
print("Index of Min Value:", b.argmin())

print('\n\n-- ALONG AXIS 0 --')
print("Max:", b.max(axis=0))
print("Min:", b.min(axis=0))
print("Mean:", b.mean(axis=0))
print("Std:", b.std(axis=0))
print("Index of Max Value:", b.argmax(axis=0)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=0))
print(b)
print('\n-- ALONG AXIS 1 --')
print("Max:", b.max(axis=1))
print("Min:", b.min(axis=1))
print("Mean:", b.mean(axis=1))
print("Std:", b.std(axis=1))
print("Index of Max Value:", b.argmax(axis=1)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=1))

[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]

Max: 99
Min: -24
Mean: 17.25
Std: 32.00813698629355
Index of Max Value: 1
Index of Min Value: 5


-- ALONG AXIS 0 --
Max: [ 1 99 49 31]
Min: [ -7 -24  20 -13]
Mean: [-2.33333333 28.66666667 35.33333333  7.33333333]
Std: [ 3.39934634 51.74510175 11.8977122  18.11690432]
Index of Max Value: [0 0 2 0]
Index of Min Value: [2 1 0 1]
[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]

-- ALONG AXIS 1 --
Max: [99 37 49]
Min: [  1 -24  -7]
Mean: [37.75 -0.25 14.25]
Std: [36.95520938 22.99320552 21.0638909 ]
Index of Max Value: [1 2 2]
Index of Min Value: [0 1 0]


In [49]:
s=np.array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [50]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [53]:
print(s[0], s[4], s[0:3:2])

0 16 [0 4]


In [54]:
print(s[::-1])
print(s[-4:])
print(s[-5:0:-2])

[144 121 100  81  64  49  36  25  16   9   4   1   0]
[ 81 100 121 144]
[64 36 16  4]


In [56]:
v=np.array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [57]:
v

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [58]:
print(v)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [61]:
condition= v>30
print(v)
condition

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [62]:
taking_gre_than_30=v[condition]

In [63]:
taking_gre_than_30

array([31, 32, 33, 34, 35])

In [64]:
print((v>30).sum())
print((v[condition]).sum())

5
165


In [68]:
# Assigning the elements greater than 30 to a new value
v[condition] = -1
v

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, -1, -1, -1, -1, -1]])

In [70]:
a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1])  # inplace
print('a:', a)
print('b:', b)

a: [2 3 4 5]
b: [2 3 4 5]


In [71]:
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1])
print('a:', a)
print('b:', b)

a: [2 3 4 5]
b: [1 2 3 4]


In [72]:
v

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, -1, -1, -1, -1, -1]])

In [73]:
v_copy=v.copy()

In [74]:
v_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, -1, -1, -1, -1, -1]])

In [87]:
#RANDOM MODULE
import random
print(random.randint(0,10)) #CHOOSES A RANDOM VARIABLE IN INTERVAL [0,10)
#NUMPY MODULE RANDOM.RANDINT
test = np.random.randint(0, 10, (4,3))  #SIZE IS DEFINED
test

9


array([[5, 2, 9],
       [3, 3, 1],
       [2, 4, 2],
       [5, 3, 4]])

In [88]:
for row in test:
    print(row)

[5 2 9]
[3 3 1]
[2 4 2]
[5 3 4]


In [89]:
for index in range(len(test)):
    print("Row {} is {}".format(index, test[index]))

Row 0 is [5 2 9]
Row 1 is [3 3 1]
Row 2 is [2 4 2]
Row 3 is [5 3 4]


In [90]:
for i, row in enumerate(test):
        print("Row {} is {}".format(i, row))

Row 0 is [5 2 9]
Row 1 is [3 3 1]
Row 2 is [2 4 2]
Row 3 is [5 3 4]


In [91]:
TEST=test**2

In [92]:
TEST

array([[25,  4, 81],
       [ 9,  9,  1],
       [ 4, 16,  4],
       [25,  9, 16]], dtype=int32)

In [93]:
test

array([[5, 2, 9],
       [3, 3, 1],
       [2, 4, 2],
       [5, 3, 4]])

In [94]:
for i,j in zip(test, TEST):
    print(i, '+', j, '=', i+j)

[5 2 9] + [25  4 81] = [30  6 90]
[3 3 1] + [9 9 1] = [12 12  2]
[2 4 2] + [ 4 16  4] = [ 6 20  6]
[5 3 4] + [25  9 16] = [30 12 20]
